### ISSUE TITLE
Nejasno definisan format unosa naziva

### ISSUE THREAD

**Issue by mersedaooad** [SoftverInzenjeringETFSA/SI2015Tim3#10]
**Komponenta**:  Forma za unos novog poslovnog partnera:

![image](https://cloud.githubusercontent.com/assets/11328979/15291048/6ab7a4aa-1b7c-11e6-82a3-7d22c357751b.png)

**commit ID:** 1bf0fdf154bfde6d025a9eb7c41a4346e5f47ae9

**Opis problema:**

Nije jasno definisano u kojem formatu treba biti naziv, npr "naziv" sa malim slovom ne radi, a u polje adresa malo slovo ne predstavlja problem.
Slika koja pokazuje da malo slovo u adresi ne predstavlja problem:

![image](https://cloud.githubusercontent.com/assets/11328979/15291140/b2b9ea06-1b7c-11e6-99de-9be8fd00fcf1.png)

**Koraci za reproduciranje problema:**
1. Pokrenuti desktop aplikaciju "App.java".
2. Ulogovati se kao uposlenik Username: uposlenik, Password:1234.
3. Odabrati opciju "Dodaj novog dobavljaca".
4. U polje naziv unijeti "naziv".
5. U polje adresa unijeti "adresa".
6. U polje JIB "1234567890987".
7.Kliknuti na dugme "Unesi".

**Comment by ncongo** [comment]
Ispravljeno
