### ISSUE TITLE
Neispravno prikazana poruka po (ne)uspješnosti generisanja izvještaja 

### ISSUE THREAD

**Issue by ajdinm** [SoftverInzenjeringETFSA/SI2015Tim3#12]
Opis problema:

Greška koja daje informaciju o (ne)ispravno generisanom izvještaju ostaje prikazana i kada se vrati na tab "Pregled trenutnog stanja robe"

Koraci za reproduciranje problema:
1. Pokrenuti desktop aplikaciju App.java
2. Unos u login vrijednosti kolona username i password : (menadzer, 1234)
3. Odabrati tab "Generisanje Izvještaja"
4. Odabrati "Skladište Sarajevo", označiti "Sumarni izvještaj" i označiti "Trenutno stanje skladišta"
5. Kliknuti "Generiši izvještaj"
6. Zatvoriti izvještaj, te se vratiti na aplikaciju
7. Preći na "Pregled trenutnog stanja robe" tab
8. Izabrati "Skladište Sarajevo" (ili bilo koje drugo skladište)

Dobijeni rezultat:

Poruka "izvještaj je kreiran" je prikazana i donjem dijelu ekrana, što sugeriše pogrešnu informaciju.

Očekivani rezultat:

Informacija relevatna za odabrani pogled ili odsutvo iste, ali ne neispravna informacija.
http://pokit.org/get/img/09bbd66210ef0380ad749416187be571.png

**Comment by ncongo** [comment]
Bug prijavljen issue #16 . Ispravljeno.
