### ISSUE TITLE
Pretraga dokumenata

### ISSUE THREAD

**Issue by ajdinm** [SoftverInzenjeringETFSA/SI2015Tim3#13]
Opis problema:

Prikazivanje dokumenata javlja izuzetak.

Koraci za reproduciranje problema:
1. Pokrenuti desktop aplikaciju App.java
2. Unos u login vrijednosti kolona username i password : (menadzer, 1234)
3. Odabrati tab "Dokumenti"
4. Odabrati "Nabavka", za vremenski period odabrati od 1.1.2016. do 16.5.2016.
5. Kliknuti "Pretraži"
6. Iz ponuđene liste odabrati prvu nabavku (greška je sa svakom od njih)
7. Kliknuti "Prikaži dokument"

Dobijeni rezultat:

Exeception koji upozorava na nepostoji file.
 http://pokit.org/get/img/52a6844c24c4b5b57a5078fa472da30f.png

Očekivani rezultat:

Prikaz izabranog dokumenta u pdf formatu.

**Comment by ncorovic1** [comment]
Problem je sto je navedena putanja za Windows operativni sistem, a kod tebe je Linux koliko mogu vidjeti iz prilozene slike. 
Za windows radi ispravno:
http://pokit.org/get/?be0745c6b49f4c5a0434a0960b8d2a5b.jpg
Za Linux bi trebalo da radi nakon dodavanja sljedeceg koda, pa bih te zamolio da provjeris opet.
http://pokit.org/get/?90344525016ccae72ef5db868c83bc9f.jpg

UPDATE: Rijeseno.
