### ISSUE TITLE
Format unosa bar-koda

### ISSUE THREAD

**Issue by mersedaooad** [SoftverInzenjeringETFSA/SI2015Tim3#14]
**Komponenta:** Unos robe
![image](https://cloud.githubusercontent.com/assets/11328979/15291669/5ff590d8-1b7f-11e6-995e-e4d41cba80df.png)

**commit ID:** 1bf0fdf154bfde6d025a9eb7c41a4346e5f47ae9

**Opis problema:** nije definisan format bar-koda u SRS dokumentu niti prilikom prijave greške na formi.

**Koraci za reproduciranje problema:**
1. Pokrenuti desktop aplikaciju "App.java".
2. Logovati se kao uposlenik.
3. Izabrati "Unos robe".
4. U polje "Bar kod" unijeti 121.
5. Izabrati "Novi artikal".
6. U ostala polja unijeti kao na slici
5. Kliknuti na dugme "Dodaj novi".

**Dobijeni rezultat:**
U donje lijevom uglu se prikazuje greška o neispravnosti bar koda.

**Očekivani rezultat:**
Jasnija poruka o formatu koji se treba unijeti.

**Comment by deancupovic** [comment]
Ne možemo u grešci opisivati kompletan EAN format bar koda
