### ISSUE TITLE
Otpremanje istog artikla vise puta

### ISSUE THREAD

**Issue by ajdinm** [SoftverInzenjeringETFSA/SI2015Tim3#15]
Opis problema:

Unos istog artikla za otpremu dovodi do exceptiona.

Koraci za reproduciranje problema:
1. Pokrenuti desktop aplikaciju App.java
2. Unos u login vrijednosti kolona username i password : (uposlenik, 1234)
3. Odabrati tab "Otpremanje robe"
4. Odabrati "API" kao kupca, unijeti barkod "1234567890001", kolicina 1, prodajnu cijenu ostaviti 1.17
5. Kliknuti dodaj za otpremu
6. Opet izabrati "API" kao kupca, unijeti "1234567890001" kao barkod, izbari kolinicu 4, i ostaviti 1.17 kao prodajnu cijenu. 
7. Kliknuti "Dodaj za otpremu"

Dobijeni rezultat:

Nullpointer exception. http://pokit.org/get/img/256ee4b649d50b5f0beee44ca778369d.png

Očekivani rezultat:

Update kolicine artikla u listi (ili novi red koji ukazuje na promjenu).

**Comment by ncongo** [comment]
Ispravljeno
