### ISSUE TITLE
Poruka o grešci se prikazuje na svim tabovima

### ISSUE THREAD

**Issue by mersedaooad** [SoftverInzenjeringETFSA/SI2015Tim3#16]
**Komponenta:** Uposlenikova forma

**commit ID:** 1bf0fdf154bfde6d025a9eb7c41a4346e5f47ae9

**Opis problema:** Prilikom pravljenja greške u unosu, prelaskom s taba na tab poruka greške se nastavlja prikazivati na svim tab-ovima.
![image](https://cloud.githubusercontent.com/assets/11328979/15291965/048c7778-1b81-11e6-925b-5965d79b6eee.png)

![image](https://cloud.githubusercontent.com/assets/11328979/15291985/109b1358-1b81-11e6-9301-5b8af1650af0.png)

**Koraci za reproduciranje problema:**
1. Pokrenuti desktop aplikaciju "App.java" .
2. Logovati se kao uposlenik.
3. Kliknuti na tab "Otpis robe".
4. U polje "komentar" unijeti "asdasd".
5. Kliknuti na dugme "Završi otpis".
6. Preći na neki drugi tab.

**Dobijeni rezultat:**
Prijava greške na svim tabovima.

**Comment by ncongo** [comment]
Ispravljeno
