### ISSUE TITLE
Menadzer - Pregled trenutnog stanja robe - ne radi

### ISSUE THREAD

**Issue by MerimaCisija** [SoftverInzenjeringETFSA/SI2015Tim3#18]
Komponenta:
Forma za menadzera

commit ID:
77d2753e444ae67160ca69a958f4d89555bb5f78

Opis problema:
Funkcionalnost Pregled trenutnog stanja robe ne radi.

Koraci za reproduciranje problema:
1. Login kao menadžer (username: menadzer, password:1234)
2. Izabrati tab Pregled trenutnog stanja robe
3. Izabrati Skladište Sarajevo (ili bilo koje drugo)

Dobijeni rezultat:
- Ne ispisuju se nikakvi podaci na formi iako u bazi ima nekoliko artikala povezaniih sa skladištem Skladište Sarajevo (http://prnt.sc/b4sw08)

Očekivani rezultat:
- Očekuje se prikaz tabele sa podacima o artiklima na skladištu Sarajevo

**Comment by ncongo** [comment]
Bug vec prijavljen. Issue #11 .
