### ISSUE TITLE
Menadžer: Dokumenti - Pretraga dokumenata ne daje ispravne rezultate

### ISSUE THREAD

**Issue by MerimaCisija** [SoftverInzenjeringETFSA/SI2015Tim3#20]
Komponenta:
MendazerDokumentiUI

commit ID:
69d878bc8f9a79499721baa8123b5bca9f88fdaa

Opis problema:
Pretraga dokumenata ne daje ispravne rezultate. Npr. ukoliko se izaberu otpremnice i dalje je rezultat pretrage lista nabavki

Koraci za reproduciranje problema:
1. Login kao menadžer (username: menadzer, password: 1234)
2. Izabrati tab Dokumenti
3. Izabrati Otpremnica
4. Izabrati vremenski period (npr. od 1.april 2016. do 7.maj 2016. )
5. Kliknuti na dugme Pretraži

Dobijeni rezultat:
Lista dokumenata nabavki (http://prnt.sc/b4ti9f)

Očekivani rezultat:
Lista otpremnica, odnosno prazna lista budući da u bazi nema otpremnica.

**Comment by ncorovic1** [comment]
Rijeseno: http://pokit.org/get/?cd4fa4ae5b75fd9e41d77199ff7dbf83.jpg
