### ISSUE TITLE
Validacija adrese

### ISSUE THREAD

**Issue by MerimaCisija** [SoftverInzenjeringETFSA/SI2015Tim3#21]
Komponenta:
UposlenikUnosPartneraUI (i druge na kojima se unosi adresa)

commit ID:
e6d47566149f291876d99a9f760e4820b651849f

Opis problema:
Validacija adrese nije ispravna. U SRS-u nisam našla format koji treba da zadovoljava adresa. Neke stvarne adrese ne zadovoljavaju validaciju (primjer ispod).

Koraci za reproduciranje problema:
1. Login kao uposlenik (username: uposlenik, password: 1234)
2. Izabrati tab Unos robe
3. Klik na dugme Dodaj novog nabavljača
4. U polje Naziv unijeti Novi Nabavljac
5. U polje adresa unijeti Zmaja od Bosne bb
6. U polje JIB unijeti 1234567890123
7. Klik na dugme Unesi

Dobijeni rezultat:
Labela koja upozorava da adresa nije ispravna (http://prnt.sc/b4tovx)

Očekivani rezultat:
Obavještenje da je nabavljač unesen.

**Comment by ncongo** [comment]
Bug je bio i rijesen je u sklopu issue #10. Potrebno je preuzeti najnoviju verziju projekta.
http://prntscr.com/b4uaua
