### ISSUE TITLE
Radnik u skladištu: Otpremanje robe - dodani artikli se ne prikazuju u tabeli

### ISSUE THREAD

**Issue by MerimaCisija** [SoftverInzenjeringETFSA/SI2015Tim3#23]
Komponenta:
UposlenikOtpremanjeUI

commit ID:
f542fd1c9fcdd3f8b07b06ba6616747a7db4f181

Opis problema:
Prilikom otpremanja robe, dodani artikli se ne prikazuju u tabeli.

Koraci za reproduciranje problema:
1. Login kao uposlenik (username: uposlenik, password: 1234)
2. Izabrati tab Otpremanje robe
3. Unos podataka za otpis (npr. kupac API, barkod 1234567890006, količina 10, prodajna cijena 2.15)
4. Klik na dugme Dodaj za otpremu
5. U polje adresa unijeti Zmaja od Bosne bb
6. U polje JIB unijeti 1234567890123
7. Klik na dugme Unesi

Dobijeni rezultat:
Prazna tabela (http://prnt.sc/b4uvim)

Očekivani rezultat:
Novi red u tabeli sa podacima artikla za otpremu

**Comment by ncongo** [comment]
Ako možeš samo ponoviti korake jer mi malo nije jasno.
Nakon što si uradila korake 1, 2 i 3, u koraku 4 se podaci smještaju u tabeli.

Ne razumijem korake 5, 6 i 7 budući da se oni ne unose na formi na kojoj se biraju podaci za otpremanje artikala.

**Comment by MerimaCisija** [comment]
Korake 5, 6 i 7 treba zanemariti, oni su poljedica kopiranja.

**Comment by ncongo** [comment]
Ispravljeno u najnovijoj verziji.

http://prntscr.com/b4vend
http://prntscr.com/b4veuk
