### ISSUE TITLE
Pretraga dokumenata dopusta neispravan datum

### ISSUE THREAD

**Issue by ajdinm** [SoftverInzenjeringETFSA/SI2015Tim3#24]
Opis problema:

Prikazivanje dokumenata javlja izuzetak.

Koraci za reproduciranje problema:
1. Pokrenuti desktop aplikaciju App.java
2. Unos u login vrijednosti kolona username i password : (menadzer, 1234)
3. Odabrati tab "Dokumenti"
4. Odabrati "Nabavka", za vremenski period odabrati od 25.5.2016. do 28.5.2016.
5. Kliknuti "Pretraži"

Dobijeni rezultat:

Poruka o usješnoj pretragi.
http://pokit.org/get/img/a743021049233d62e995b54339b8ce01.png
Očekivani rezultat:

Poruka o nekorektnim parametrima.

**Comment by ncorovic1** [comment]
Rijeseno: http://pokit.org/get/?817361b02b2a23ea759e017fc3d10378.jpg
