### ISSUE TITLE
Radnik u skladištu: Pregled trenutnog stanja robe - ne radi

### ISSUE THREAD

**Issue by MerimaCisija** [SoftverInzenjeringETFSA/SI2015Tim3#25]
Komponenta:
Froma za uposlenika

commit ID:
77d2753e444ae67160ca69a958f4d89555bb5f78

Opis problema:
Ne prikazuje se pregled trenutnog stanja robe za uposlenika

Koraci za reproduciranje problema:
1. Login kao uposlenik (username: uposlenik, password: 1234)
2. Izabrati tab Pregled trenutnog stanja robe

Dobijeni rezultat:
Prazna tabela (http://prnt.sc/b4v32v)

Očekivani rezultat:
Tabela sa podacima o artiklima u skladištu

**Comment by ncongo** [comment]
Prijavljen bug u issue #22
