### ISSUE TITLE
Unhandled exception: Unos nepostojeceg artikla 

### ISSUE THREAD

**Issue by ajdinm** [SoftverInzenjeringETFSA/SI2015Tim3#26]
Opis problema:
Neprikazivanje trenutnog artikala unutar skladista u kojima radnik radi

Koraci za reproduciranje problema:
1. Pokrenuti desktop aplikaciju App.java
2. Unos u login vrijednosti kolona username i password : (uposlenik, 1234)
3. Unijeti barkod 1234567890012 (koji ne postoji u bazi)
4. Odabrati dobavljaca "API", opet unijeti isti barkod (1234567890012), i izabrati nabavnu cijenu 31.
5. Kliknuti Dodaj

Dobijeni rezultat:

Unhanded exception
(http://pokit.org/get/img/67d5a7919792de4f7bb27427d841c401.png)

Očekivani rezultat:

Poruka o greški

**Comment by mirzetb** [comment]
Nisam siguran da razumijem bug. Prvi textbox Bar kod je za unos bar koda nabavke, a textbox bar kod unutar dijela 'Unos artikla' je za pojedine artikle. Da li je to odgovor? Kod tebe se to dobro ne vidi jer je nesto sve uvecano.. Ovako kod mene izgleda: http://pokit.org/get/?4d2990306ee673a31e838c2c5dfa8241.jpg

**Comment by ajdinm** [comment]
Kojoj koloni koje tabele odgovara kod nabavke ?

**Comment by mirzetb** [comment]
Kod unosa robe u tabeli su samo informacije o artiklima. Nigdje se (osim u textboxu za unos) ne vidi bar kod nabavke. Mislim da postoji bug, ali nije ono sto ti pitas :P
