### ISSUE TITLE
Editable Lista uposlenika

### ISSUE THREAD

**Issue by encore13** [SoftverInzenjeringETFSA/SI2015Tim3#29]
Komponenta:
Tab uposlenici

commit ID:
1bf0fdf154bfde6d025a9eb7c41a4346e5f47ae9

Opis problema:

Tabela 'Lista uposlenika' je editable dvoklikom na bilo koju ćeliju (promjena se doduše ne sprema u bazu)

Koraci za reproduciranje problema:
1. Pokrenuti aplikaciju
2. Prijaviti se kao menadžer
3. Kliknuti na bilo koje polje tabele, podaci se mogu prepravljati i brisati. 

Screenshot:

http://prntscr.com/b4ve00

Očekivano: Da korisnik nije u stanju poigravati se sa podacima na bilo koji način.

Edit: kao i ostale liste na ovom view-u.

**Comment by ncongo** [comment]
Ispravljeno
