### ISSUE TITLE
Labela za prikaz ulogovanog korisnika

### ISSUE THREAD

**Issue by mersedaooad** [SoftverInzenjeringETFSA/SI2015Tim3#30]
**Komponenta:** Menadzer forma

**Commit ID:** ed10472de60a5bf2ad333280d0ba1bcd01f5d2fc

**Opis problema:** Nedovoljno prosirena labela za ispisvanje imena ulogovanog korisnika sistema.

**Koraci za reproduciranje problema:**
1. Pokrenuti desktop aplikaciju "App.hava".
2. Ulogovati se kao menadzer.

**Dobijeni rezultat:**
 ![image](https://cloud.githubusercontent.com/assets/11328979/15304004/278ff666-1bbb-11e6-8c59-9b4b39d54379.png)

**Comment by ncongo** [comment]
Bug je rijesen u posljednjoj verziji projekta. Potrebno je preuzeti posljednju verziju.
http://prntscr.com/b4vkwr
