### ISSUE TITLE
Lista uposlenika (i skladišta) omogućava multiple selection

### ISSUE THREAD

**Issue by encore13** [SoftverInzenjeringETFSA/SI2015Tim3#31]
Komponenta:
Tab uposlenici

commit ID:
1bf0fdf154bfde6d025a9eb7c41a4346e5f47ae9

Opis problema:

Tabela 'Lista uposlenika' omogućava selektovanje više uposlenika a pri brisanju samo
prvi od selektovanih se zaista obriše.

Koraci za reproduciranje problema:
1. Pokrenuti aplikaciju
2. Prijaviti se kao menadžer
3. Kliknuti na jednog a zatim držanjem i prevlačenjem miša selektovati još nekoliko
uposlenika.
4. Kliknuti na dugme "Obriši uposlenika" 

Očekivano: Onemogućiti multiple row selections u tabeli (kao i u tabeli skladišta i sl.)

**Comment by ncongo** [comment]
Ispravljeno
