### ISSUE TITLE
Nabavna cijena > prodajne ??

### ISSUE THREAD

**Issue by encore13** [SoftverInzenjeringETFSA/SI2015Tim3#33]
Komponenta:
Tab Unos robe

commit ID:
1bf0fdf154bfde6d025a9eb7c41a4346e5f47ae9

Opis problema:

Pri unosu novog artikla dopušteno da nabavna cijena bude veća od prodajne što nema logike
s ekonomske strane poslovanja :)

Koraci za reproduciranje problema:
1. Pokrenuti aplikaciju
2. Prijaviti se kao uposlenik
3. Kliknuti na tab "Unos robe"
4. Kliknuti na radiobutton "Novi artikal"
5. Popuniti tražene podatke sa nabavnom cijenom većom od prodajne
6. Kliknuti na dugme "Dodaj novi"

**Comment by ncongo** [comment]
Nabavna cijena i prodajna cijena su cijene koje na tržištu variraju, tako da je moguće da nabavna cijena bude veća od prodajne cijene.
Također pogledaj SRS, kupac nije izričito tražio da sistem ima validaciju da nabavna cijena ne smije biti veća od prodajne.
