### ISSUE TITLE
Nema ERD 

### ISSUE THREAD

**Issue by MerimaCisija** [SoftverInzenjeringETFSA/SI2015Tim3#34]
Postoji class dijagram, ali ne i ERD.

**Comment by mirzetb** [comment]
Prema zadatku 'Dizajn sistema' (http://pokit.org/get/?08433d3744b8e53338b1f00ad782bd8b.jpg) jedini obavezan dijagram je class.

**Comment by MerimaCisija** [comment]
Obavezni su svi dijagrami potrebni za implementaciju i održavanje. Ukoliko tim003 smatra ERD bespotrebnim, o tome bi se dalo diskutovati (što nećemo ovom prilikom :) ).

**Comment by mirzetb** [comment]
Tim003 je duboko ubijedjen da je ERD u ovom projektu bio nepotreban, pogotovo zbog nacina na koji se pravila baza - mapiranjem klasa preko hibernate-a. :P
