### ISSUE TITLE
Brisanje skladišta u kojem ima zaposlenih

### ISSUE THREAD

**Issue by encore13** [SoftverInzenjeringETFSA/SI2015Tim3#35]
Komponenta:
Tab Skladišta

commit ID:
1bf0fdf154bfde6d025a9eb7c41a4346e5f47ae9

Opis problema:

Pri brisanju skladišta koje ima uposlenika dolazi do bacanja izuzetka,
a nikakav feedback nakon pritiska dugmeta "Obriši skladište" nije dostupan..

Koraci za reproduciranje problema:
1. Pokrenuti aplikaciju
2. Prijaviti se kao menadžer
3. Kliknuti na tab "Skladišta"
4. Odabrati neko skladište koje ima uposlenika npr. Skladište Mostar
5. Kliknuti na dugme "Obriši skladište"

Dobijeno: exception
Očekivano: Poruka o nemogućnosti brisanja skladišta sve dok u njemu
postoje zaposlenici i obrada exceptiona

Screenshot:
http://prnt.sc/b4w8pi

**Comment by ncorovic1** [comment]
Rijeseno: http://pokit.org/get/?e6a619d6ffd1cbae22f1435866122fbd.jpg
