### ISSUE TITLE
Uposlenik: Otpis robe: Prikazuje se da je prevelika količina iako nije

### ISSUE THREAD

**Issue by MerimaCisija** [SoftverInzenjeringETFSA/SI2015Tim3#36]
Komponenta:
OtpisRobeUI

commit ID:
fcd173206e4ad8e608f00d0e523efa0f5b637396

Opis problema:
Prilikom otpisa manje količine robe, u odnosu na onu u bazi, ispisuje se da je količina prevelika. 

Koraci za reproduciranje problema:
1. Login kao uposlenik(username: uposlenik, password: 1234)
2. Izabrati tab Otpis robe
3. Unijeti podatke kao na slici ispod
4. Klik na dugme Dodaj

Dobijeni rezultat:
Labela sa upozorenjem da je količina robe prevelika (http://prnt.sc/b4wk6v, http://prnt.sc/b4wmm7)

Očekivani rezultat:
Dodavanje stavke u tabelu.

**Comment by mirzetb** [comment]
U kojem skladistu radi uposlenik 'uposlenik'?

**Comment by mirzetb** [comment]
Uposlenik moze otpisati samo artikle iz svog skladista, tako da unos bilo koje kolicine bilo kojeg artikla koji nije iz skladista u kojem radi uposlenik, predstavlja 'preveliku kolicinu'.
