### ISSUE TITLE
Nedostaje dobavljac u combobox-u nakon sto ga prethodno dodamo (Unos robe)

### ISSUE THREAD

**Issue by eminaprlja** [SoftverInzenjeringETFSA/SI2015Tim3#39]
Komponenta:
Sistem za upravljanje skladistem- Radnik u skladistu/ Otpremanje robe

commit ID:
ccd392e

Opis problema:

Nakon sto se logujemo kao radnik i dodamo novog dobavljaca, isti se ne prikazuje u combobox-u gdje su ostali dobavljaci, a prethodno dobijemo obavjestenje da je dodavanje uspjesno realizovano.

Koraci za reproduciranje problema:
1. Pokrenuti aplikaciju
2. Prijaviti se kao radnik
3. Kliknuti na tab Unos Robe
4. Kliknuti na dugme "Dodaj novog dobavljaca"
5. Popuniti podatke Naziv, Adresa, JIB ("Neki", "Neka", 1234567891234")
6. Kliknuti dugme Unesi
7. Kliknuti na combobox i vidjeti da nema unesenog dobavljaca

Dobijeno:

```
Nepotpuna lista dobavljaca
```

Očekivano:

```
Prethodno dodani dobavljac se nalazi na listi svih dobavljaca
```

**Comment by mirzetb** [comment]
Fixed 0120068.
