### ISSUE TITLE
Ciscenje svih polja kad se pogrijesi unos prodajne cijene

### ISSUE THREAD

**Issue by eminaprlja** [SoftverInzenjeringETFSA/SI2015Tim3#41]
Komponenta:
Sistem za upravljanje skladistem- Radnik u skladistu/ Otpremanje robe

commit ID:
ccd392e

Opis problema:

Nakon sto se logujemo kao radnik otvorimo tab Otpremanje robe. Unesemo bar kod, kolicinu i u polje prodajna cijena unesemo slova, kliknemo dugme Dodaj za otpremu aplikacija, sva polja se obrisu i ponovo se mora sve unositi umjesto notifikacije da prodajna cijena nije broj i brisanja samo tog polja ili nesto tako slicno.

Koraci za reproduciranje problema:
1. Pokrenuti aplikaciju
2. Prijaviti se kao radnik
3. Kliknuti na tab Otpremanje robe
4. Unijeti sljedece podatke za bar kod, kolicinu i prodajnu cijenu: 34324324, 1, adsds
5. Kliknuti na dugme "Dodaj za otpremninu"

Dobijeno:

Sva polja prebrisana i notifikacija o pogresnom formatu prodajne cijene

Očekivano:

Notifikacija o pogresnom formatu prodajne cijene i samo to polje prebrisano ili sva polja ostavljena kakva jesu

**Comment by ncongo** [comment]
Ispravljeno
