### ISSUE TITLE
Nije adekvatna boja validacije unosa uposlenika

### ISSUE THREAD

**Issue by eminaprlja** [SoftverInzenjeringETFSA/SI2015Tim3#43]
Komponenta:
Sistem za upravljanje skladistem- Menadzeer/ Uposlenici

commit ID:
ccd392e

Opis problema:

Nakon sto se logujemo kao menadzer otvorimo tab Uposlenici. Ako samo kliknemo na dugme Dodaj novog uposlenika pojavi se zelena labela "Nije uneseno ime!". U ovoj situaciji bi bila adekvatna crvena labela kao znak da nesto nije u redu. 

Koraci za reproduciranje problema:
1. Pokrenuti aplikaciju
2. Prijaviti se kao menadzer
3. Kliknuti na tab Uposlenici
5. Kliknuti na dugme Dodaj novog uposlenika

Dobijeno:

Zeleno obavjestenje o pogresnom unosu

Očekivano:

Crveno obavjestenje o pogresnom unosu

**Comment by ncongo** [comment]
Ispravljeno
