### ISSUE TITLE
Pretraga dokumenata izbacuje prozor "Greska", a rezultati uredno nadjeni

### ISSUE THREAD

**Issue by eminaprlja** [SoftverInzenjeringETFSA/SI2015Tim3#44]
Komponenta:
Sistem za upravljanje skladistem- Menadzeer/ Dokumenti

commit ID:
ccd392e

Opis problema:

Nakon sto se logujemo kao menadzer otvorimo tab Dokumenti. Selektujemo tip dokumenta, odaberemo datum od i datum do, kliknemo dugme Pretrazi, dobijemo prozor sa nazivom "Greska", a informacija je "Pretraga zavrsena!". Lista se popunila rezultatima i rezultati su validni, tako da naslov ne bi trebao biti "Greska" nego "Obavjestenje" ili nesto slicno, kako korisnik ne bi bio zbunjen.

Koraci za reproduciranje problema:
1. Pokrenuti aplikaciju
2. Prijaviti se kao menadzer
3. Kliknuti na tab Dokumenti
4. Odabrati Tip dokumenta npr. Otpremnica i Otpisnica, odabrati od i do datume i kliknuti dugme Pretrazi

Dobijeno:

Prozor koji obavjestava o greski

Očekivano:

Obavjestenje o uspjesnoj pretrazi

![5](https://cloud.githubusercontent.com/assets/8864891/15439273/6f0e4642-1ed0-11e6-853f-722677b7a3da.jpg)

**Comment by ncongo** [comment]
Ispravljeno
