### ISSUE TITLE
Poruke o greskama prilikom validacije polja se preklapaju

### ISSUE THREAD

**Issue by eminaprlja** [SoftverInzenjeringETFSA/SI2015Tim3#45]
Komponenta:
Sistem za upravljanje skladistem- Menadzeer/ Skladista /Uposlenici

commit ID:
ccd392e

Opis problema:

Nakon sto se logujemo kao menadzer otvorimo tab Skladista. Kliknemo na dugme Dodaj skladiste (bez prethodno unesenih podataka). Pojavljuje se u donjem lijevom uglu poruka da nismo unijeli naziv skladista. Nako toga predjemo na tab Uposlenici, ista greska ostaje. Kliknemo dugme Dodaj novog zaposlenika (bez pretnodno unesenih podataka) i na istom mjestu gdje je prethodno bila poruka pojavljuje se nova poruka koja se ne vidi od prethodne. 

Koraci za reproduciranje problema:
1. Pokrenuti aplikaciju
2. Prijaviti se kao menadzer
3. Kliknuti na tab Skladista
4. Klik na dugme Dodaj skladiste
5. Prelazak na tab Uposlenici
6. Klik na dugme Dodaj novog uposlenika

Dobijeno:

Poruke o greskama koje se preklapaju

Očekivano:

Uklanjanje prethodne poruke o greski i prikazivanje nove

![6](https://cloud.githubusercontent.com/assets/8864891/15439607/9b8542ce-1ed1-11e6-98b9-530ec18b20ba.jpg)

**Comment by ncongo** [comment]
Ispravljeno
