### ISSUE TITLE
Artikli

### ISSUE THREAD

**Issue by deancupovic** [SoftverInzenjeringETFSA/SI2015Tim3#6]
Šta je sa artiklima, ko unosi i gdje se unose? Kako znate da je riječ o istom artiklu? Prodajna cijena i jedinica mjere?

**Comment by NerminBoja** [comment]
Je li moguće da neke od ovih stvari vec imaju pod 3.1.3. Zaprimanje robe u skladište?
Tu je navedena jedinica mjere, unos pojedinog artikla.

**Comment by deancupovic** [comment]
Ok ima, međutim nije specificirano ko unosi.
